name: Quality Assurance

'on':
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3
            -
                run: make lint
